name: Deploy to production environment - www.foia.gov
on:
  push:
    branches:
      - master
jobs:
  # Build for the Acquia Cloud production environment
  build:
    env:
      GIT_REPO: ${{ secrets.GIT_REPO }}
      NODE_ENV: production
      APP_ENV: production
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup RUBY
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: | 
          npm i
          bundle install
      # Install SSH Key
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Acquia known hosts
        run: |
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
      - name: Install npm packages
        run: |
          npm i
      - name: Building front end site
        run: |
          make build
      - name: Run tests
        run: make test
      - name: Deploy to Acquia development
        run: sh bin/git-deploy.sh _site master
