name: Pull Request into dev
on:
  pull_request:
    branches:
      - dev-test
jobs:
  # Build for the Acquia Cloud development environment
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Running tests
        run: |
          make test
      - name: attach_workspace test
        uses: actions/download-artifact@v3
        with:
          name: setsite
